Add suppliers section
NadieKir/product-management-app pull request #9
Opened 2024-05-18 16:55 UTC by NadieKir

- Add product suppliers table
- Implement adding supplier by choosing existing one
- Implement adding supplier by creating new one
- Implement deleting suppliers

2024-05-20 07:31 UTC, Nastassia24 commented on webapp/api/countriesService.js
> +sap.ui.define([], function () {
test comment

2024-05-20 13:55 UTC, Nastassia24 requested changes

2024-05-20 13:55 UTC, Nastassia24 commented on webapp/api/countriesService.js
> +  async function handleFetch(sUrl, oRequestOptions = {}, fErrorHandler) {
why do you define 3 parameters, but when you call that function, you pass always 1 param. it means that oRequestOptions and fErrorHandler are not used

2024-05-20 13:55 UTC, Nastassia24 commented on webapp/controller/BaseController.js
> +            return undefined;
you don't need return undefined implicitly

2024-05-20 13:55 UTC, Nastassia24 commented on webapp/controller/BaseController.js
> +      removeDependentDialog: function (oDialog) {
this method is only used in ProductDetailsPage

2024-05-23 09:32 UTC, SamusNiko approved these changes

2024-05-23 09:42 UTC, merged